services:
  - type: web
    name: n8n
    env: docker
    plan: free
    repo: https://github.com/aagdigitalco-creator/n8n
    branch: master
    dockerfilePath: ./Dockerfile
    envVars:
      - key: N8N_HOST
        value: n8n.onrender.com
      - key: N8N_PORT
        value: 5678
      - key: PORT
        value: 5678
      - key: N8N_PROTOCOL
        value: https
      - key: NODE_ENV
        value: production
